_BASE_: [
  '../datasets/voc_cell.yml',
  '../runtime.yml',
  '../ppyoloe/_base_/ppyoloe_crn.yml',
  '../ppyoloe/_base_/ppyoloe_reader.yml',
]
depth_mult: 0.25
width_mult: 0.50

log_iter: 100
snapshot_epoch: 5
weights: output/convnext/model_final
pretrain_weights: /public/home/hpc214712266/logo_detection/paddle/detection/PaddleDetection/convnext_tiny_22k_224.pdparams


YOLOv3:
  backbone: ConvNeXt
  neck: CustomCSPPAN
  yolo_head: PPYOLOEHead
  post_process: ~

ConvNeXt:
  arch: 'tiny'
  drop_path_rate: 0.4
  layer_scale_init_value: 1.0
  return_idx: [1, 2, 3]


PPYOLOEHead:
  static_assigner_epoch: 12
  nms:
    nms_top_k: 10000
    keep_top_k: 300
    score_threshold: 0.01
    nms_threshold: 0.7


TrainReader:
  batch_size: 1


epoch: 100
LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [36]
    use_warmup: false

OptimizerBuilder:
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0005
