_BASE_: [
  '../datasets/voc_cell.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/ppyoloe_crn.yml',
  './_base_/ppyoloe_reader.yml',
]

log_iter: 100
snapshot_epoch: 10
weights: output/ppyoloe_crn_x_300e_coco/model_final

pretrain_weights: /public/home/hpc214712266/logo_detection/paddle/detection/PaddleDetection/CSPResNetb_x_pretrained.pdparams
depth_mult: 1.33
width_mult: 1.25
