
metric: VOC
map_type: 11point
num_classes: 1

TrainDataset:
  name: VOCDataSet
  dataset_dir: /public/home/hpc214712266/logo_detection/paddle/voc_new_cell
  anno_path: trainval.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  name: VOCDataSet
  dataset_dir: /public/home/hpc214712266/logo_detection/paddle/voc_new_cell
  anno_path: val.txt
  label_list: label_list.txt
  data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  name: ImageFolder
  anno_path: /public/home/hpc214712266/logo_detection/paddle/voc_new_cell/label_list.txt
